// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	tag4 "grpc-project/api/simple/handler/tag"
	tag3 "grpc-project/logic/tag"
	"grpc-project/repo"
	"grpc-project/repo/tag"
	"grpc-project/server"
	tag2 "grpc-project/service/tag"
)

// Injectors from wire.go:

func initServer() (*Server, error) {
	client, err := repo.NewRedis()
	if err != nil {
		return nil, err
	}
	grpcServer := server.NewGRPC(client)
	serveMux := server.NewGateway()
	httpServeMux := server.NewHttp()
	db, err := repo.NewDB()
	if err != nil {
		return nil, err
	}
	tagRepo := tag.NewRepo(db)
	service := tag2.NewService(tagRepo)
	logic := tag3.NewLogic(service)
	handler := tag4.NewHandler(logic)
	mainServer := NewServer(grpcServer, serveMux, httpServeMux, handler)
	return mainServer, nil
}
