server:
  http:
    host: 0.0.0.0
    port: 8082
    timeout: 1s
  grpc:
    host: 0.0.0.0
    port: 0
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=192.168.51.203 user=datatom dbname=dtaccount-test sslmode=disable password=db_password port=30238 TimeZone=Asia/Shanghai
  redis:
    host: 192.168.51.203
    port: 30648