server:
  http:
    host: 127.0.0.1
    port: 8081
    timeout: 1s
  grpc:
    host: 127.0.0.1
    port: 8082
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=192.168.51.203 user=datatom dbname=%s sslmode=disable password=db_password port=30238 TimeZone=Asia/Shanghai
    defaultDbName: dtaccount-test
    dbName: asset
  redis:
    addr: 192.168.51.207:30246
log:
  file: ./matrix-service.log
  level: debug
  maxSize: 100
  backups: 3
  maxAge: 30