// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"grpc-project/server"
)

// Injectors from wire.go:

func initServer() (*Server, error) {
	grpcServer := server.NewGRPC()
	serveMux := server.NewHttp()
	mainServer := NewServer(grpcServer, serveMux)
	return mainServer, nil
}
